// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: threatattest/attestation/v1/query.proto

package pb

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryIsMaliciousRequest struct {
}

func (m *QueryIsMaliciousRequest) Reset()         { *m = QueryIsMaliciousRequest{} }
func (m *QueryIsMaliciousRequest) String() string { return proto.CompactTextString(m) }
func (*QueryIsMaliciousRequest) ProtoMessage()    {}
func (*QueryIsMaliciousRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a6fd3841a9b6466, []int{0}
}
func (m *QueryIsMaliciousRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIsMaliciousRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIsMaliciousRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIsMaliciousRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIsMaliciousRequest.Merge(m, src)
}
func (m *QueryIsMaliciousRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryIsMaliciousRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIsMaliciousRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIsMaliciousRequest proto.InternalMessageInfo

type QueryIsMaliciousResponse struct {
}

func (m *QueryIsMaliciousResponse) Reset()         { *m = QueryIsMaliciousResponse{} }
func (m *QueryIsMaliciousResponse) String() string { return proto.CompactTextString(m) }
func (*QueryIsMaliciousResponse) ProtoMessage()    {}
func (*QueryIsMaliciousResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a6fd3841a9b6466, []int{1}
}
func (m *QueryIsMaliciousResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIsMaliciousResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIsMaliciousResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIsMaliciousResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIsMaliciousResponse.Merge(m, src)
}
func (m *QueryIsMaliciousResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryIsMaliciousResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIsMaliciousResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIsMaliciousResponse proto.InternalMessageInfo

type QueryIsMaliciousURLRequest struct {
}

func (m *QueryIsMaliciousURLRequest) Reset()         { *m = QueryIsMaliciousURLRequest{} }
func (m *QueryIsMaliciousURLRequest) String() string { return proto.CompactTextString(m) }
func (*QueryIsMaliciousURLRequest) ProtoMessage()    {}
func (*QueryIsMaliciousURLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a6fd3841a9b6466, []int{2}
}
func (m *QueryIsMaliciousURLRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIsMaliciousURLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIsMaliciousURLRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIsMaliciousURLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIsMaliciousURLRequest.Merge(m, src)
}
func (m *QueryIsMaliciousURLRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryIsMaliciousURLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIsMaliciousURLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIsMaliciousURLRequest proto.InternalMessageInfo

type QueryIsMaliciousIPv4Request struct {
}

func (m *QueryIsMaliciousIPv4Request) Reset()         { *m = QueryIsMaliciousIPv4Request{} }
func (m *QueryIsMaliciousIPv4Request) String() string { return proto.CompactTextString(m) }
func (*QueryIsMaliciousIPv4Request) ProtoMessage()    {}
func (*QueryIsMaliciousIPv4Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a6fd3841a9b6466, []int{3}
}
func (m *QueryIsMaliciousIPv4Request) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIsMaliciousIPv4Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIsMaliciousIPv4Request.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIsMaliciousIPv4Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIsMaliciousIPv4Request.Merge(m, src)
}
func (m *QueryIsMaliciousIPv4Request) XXX_Size() int {
	return m.Size()
}
func (m *QueryIsMaliciousIPv4Request) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIsMaliciousIPv4Request.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIsMaliciousIPv4Request proto.InternalMessageInfo

type QueryIsMaliciousHollomanRequest struct {
}

func (m *QueryIsMaliciousHollomanRequest) Reset()         { *m = QueryIsMaliciousHollomanRequest{} }
func (m *QueryIsMaliciousHollomanRequest) String() string { return proto.CompactTextString(m) }
func (*QueryIsMaliciousHollomanRequest) ProtoMessage()    {}
func (*QueryIsMaliciousHollomanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a6fd3841a9b6466, []int{4}
}
func (m *QueryIsMaliciousHollomanRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIsMaliciousHollomanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIsMaliciousHollomanRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIsMaliciousHollomanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIsMaliciousHollomanRequest.Merge(m, src)
}
func (m *QueryIsMaliciousHollomanRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryIsMaliciousHollomanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIsMaliciousHollomanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIsMaliciousHollomanRequest proto.InternalMessageInfo

type QueryGetAttestationRequest struct {
}

func (m *QueryGetAttestationRequest) Reset()         { *m = QueryGetAttestationRequest{} }
func (m *QueryGetAttestationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAttestationRequest) ProtoMessage()    {}
func (*QueryGetAttestationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a6fd3841a9b6466, []int{5}
}
func (m *QueryGetAttestationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAttestationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAttestationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAttestationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAttestationRequest.Merge(m, src)
}
func (m *QueryGetAttestationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAttestationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAttestationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAttestationRequest proto.InternalMessageInfo

type QueryGetAttestationResponse struct {
}

func (m *QueryGetAttestationResponse) Reset()         { *m = QueryGetAttestationResponse{} }
func (m *QueryGetAttestationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAttestationResponse) ProtoMessage()    {}
func (*QueryGetAttestationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a6fd3841a9b6466, []int{6}
}
func (m *QueryGetAttestationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAttestationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAttestationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAttestationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAttestationResponse.Merge(m, src)
}
func (m *QueryGetAttestationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAttestationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAttestationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAttestationResponse proto.InternalMessageInfo

type QueryListArtifactAttestationsRequest struct {
}

func (m *QueryListArtifactAttestationsRequest) Reset()         { *m = QueryListArtifactAttestationsRequest{} }
func (m *QueryListArtifactAttestationsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListArtifactAttestationsRequest) ProtoMessage()    {}
func (*QueryListArtifactAttestationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a6fd3841a9b6466, []int{7}
}
func (m *QueryListArtifactAttestationsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListArtifactAttestationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListArtifactAttestationsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListArtifactAttestationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListArtifactAttestationsRequest.Merge(m, src)
}
func (m *QueryListArtifactAttestationsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListArtifactAttestationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListArtifactAttestationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListArtifactAttestationsRequest proto.InternalMessageInfo

type QueryListArtifactAttestationsResponse struct {
}

func (m *QueryListArtifactAttestationsResponse) Reset()         { *m = QueryListArtifactAttestationsResponse{} }
func (m *QueryListArtifactAttestationsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListArtifactAttestationsResponse) ProtoMessage()    {}
func (*QueryListArtifactAttestationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a6fd3841a9b6466, []int{8}
}
func (m *QueryListArtifactAttestationsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListArtifactAttestationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListArtifactAttestationsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListArtifactAttestationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListArtifactAttestationsResponse.Merge(m, src)
}
func (m *QueryListArtifactAttestationsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListArtifactAttestationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListArtifactAttestationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListArtifactAttestationsResponse proto.InternalMessageInfo

type QueryListAttesterAttestationsRequest struct {
}

func (m *QueryListAttesterAttestationsRequest) Reset()         { *m = QueryListAttesterAttestationsRequest{} }
func (m *QueryListAttesterAttestationsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListAttesterAttestationsRequest) ProtoMessage()    {}
func (*QueryListAttesterAttestationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a6fd3841a9b6466, []int{9}
}
func (m *QueryListAttesterAttestationsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListAttesterAttestationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListAttesterAttestationsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListAttesterAttestationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListAttesterAttestationsRequest.Merge(m, src)
}
func (m *QueryListAttesterAttestationsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListAttesterAttestationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListAttesterAttestationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListAttesterAttestationsRequest proto.InternalMessageInfo

type QueryListAttesterAttestationsResponse struct {
}

func (m *QueryListAttesterAttestationsResponse) Reset()         { *m = QueryListAttesterAttestationsResponse{} }
func (m *QueryListAttesterAttestationsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListAttesterAttestationsResponse) ProtoMessage()    {}
func (*QueryListAttesterAttestationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a6fd3841a9b6466, []int{10}
}
func (m *QueryListAttesterAttestationsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListAttesterAttestationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListAttesterAttestationsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListAttesterAttestationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListAttesterAttestationsResponse.Merge(m, src)
}
func (m *QueryListAttesterAttestationsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListAttesterAttestationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListAttesterAttestationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListAttesterAttestationsResponse proto.InternalMessageInfo

type QueryGetDisputeRequest struct {
}

func (m *QueryGetDisputeRequest) Reset()         { *m = QueryGetDisputeRequest{} }
func (m *QueryGetDisputeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDisputeRequest) ProtoMessage()    {}
func (*QueryGetDisputeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a6fd3841a9b6466, []int{11}
}
func (m *QueryGetDisputeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDisputeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDisputeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDisputeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDisputeRequest.Merge(m, src)
}
func (m *QueryGetDisputeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDisputeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDisputeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDisputeRequest proto.InternalMessageInfo

type QueryGetDisputeResponse struct {
}

func (m *QueryGetDisputeResponse) Reset()         { *m = QueryGetDisputeResponse{} }
func (m *QueryGetDisputeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetDisputeResponse) ProtoMessage()    {}
func (*QueryGetDisputeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a6fd3841a9b6466, []int{12}
}
func (m *QueryGetDisputeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDisputeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDisputeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDisputeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDisputeResponse.Merge(m, src)
}
func (m *QueryGetDisputeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDisputeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDisputeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDisputeResponse proto.InternalMessageInfo

type QueryIsBlacklistedRequest struct {
}

func (m *QueryIsBlacklistedRequest) Reset()         { *m = QueryIsBlacklistedRequest{} }
func (m *QueryIsBlacklistedRequest) String() string { return proto.CompactTextString(m) }
func (*QueryIsBlacklistedRequest) ProtoMessage()    {}
func (*QueryIsBlacklistedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a6fd3841a9b6466, []int{13}
}
func (m *QueryIsBlacklistedRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIsBlacklistedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIsBlacklistedRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIsBlacklistedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIsBlacklistedRequest.Merge(m, src)
}
func (m *QueryIsBlacklistedRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryIsBlacklistedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIsBlacklistedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIsBlacklistedRequest proto.InternalMessageInfo

type QueryIsBlacklistedResponse struct {
}

func (m *QueryIsBlacklistedResponse) Reset()         { *m = QueryIsBlacklistedResponse{} }
func (m *QueryIsBlacklistedResponse) String() string { return proto.CompactTextString(m) }
func (*QueryIsBlacklistedResponse) ProtoMessage()    {}
func (*QueryIsBlacklistedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a6fd3841a9b6466, []int{14}
}
func (m *QueryIsBlacklistedResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIsBlacklistedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIsBlacklistedResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIsBlacklistedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIsBlacklistedResponse.Merge(m, src)
}
func (m *QueryIsBlacklistedResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryIsBlacklistedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIsBlacklistedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIsBlacklistedResponse proto.InternalMessageInfo

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a6fd3841a9b6466, []int{15}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a6fd3841a9b6466, []int{16}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryIsMaliciousRequest)(nil), "threatattest.attestation.QueryIsMaliciousRequest")
	proto.RegisterType((*QueryIsMaliciousResponse)(nil), "threatattest.attestation.QueryIsMaliciousResponse")
	proto.RegisterType((*QueryIsMaliciousURLRequest)(nil), "threatattest.attestation.QueryIsMaliciousURLRequest")
	proto.RegisterType((*QueryIsMaliciousIPv4Request)(nil), "threatattest.attestation.QueryIsMaliciousIPv4Request")
	proto.RegisterType((*QueryIsMaliciousHollomanRequest)(nil), "threatattest.attestation.QueryIsMaliciousHollomanRequest")
	proto.RegisterType((*QueryGetAttestationRequest)(nil), "threatattest.attestation.QueryGetAttestationRequest")
	proto.RegisterType((*QueryGetAttestationResponse)(nil), "threatattest.attestation.QueryGetAttestationResponse")
	proto.RegisterType((*QueryListArtifactAttestationsRequest)(nil), "threatattest.attestation.QueryListArtifactAttestationsRequest")
	proto.RegisterType((*QueryListArtifactAttestationsResponse)(nil), "threatattest.attestation.QueryListArtifactAttestationsResponse")
	proto.RegisterType((*QueryListAttesterAttestationsRequest)(nil), "threatattest.attestation.QueryListAttesterAttestationsRequest")
	proto.RegisterType((*QueryListAttesterAttestationsResponse)(nil), "threatattest.attestation.QueryListAttesterAttestationsResponse")
	proto.RegisterType((*QueryGetDisputeRequest)(nil), "threatattest.attestation.QueryGetDisputeRequest")
	proto.RegisterType((*QueryGetDisputeResponse)(nil), "threatattest.attestation.QueryGetDisputeResponse")
	proto.RegisterType((*QueryIsBlacklistedRequest)(nil), "threatattest.attestation.QueryIsBlacklistedRequest")
	proto.RegisterType((*QueryIsBlacklistedResponse)(nil), "threatattest.attestation.QueryIsBlacklistedResponse")
	proto.RegisterType((*QueryParamsRequest)(nil), "threatattest.attestation.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "threatattest.attestation.QueryParamsResponse")
}

func init() {
	proto.RegisterFile("threatattest/attestation/v1/query.proto", fileDescriptor_8a6fd3841a9b6466)
}

var fileDescriptor_8a6fd3841a9b6466 = []byte{
	// 501 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xbd, 0x6f, 0xd3, 0x40,
	0x14, 0x8f, 0x07, 0x3a, 0x3c, 0x44, 0x91, 0xae, 0x7c, 0xa4, 0x57, 0x30, 0x22, 0x02, 0xba, 0x80,
	0x4d, 0xda, 0x74, 0x60, 0x01, 0xb5, 0x42, 0x82, 0x4a, 0x05, 0x95, 0x4a, 0x2c, 0x6c, 0x17, 0x73,
	0x90, 0x13, 0x4e, 0xce, 0xf1, 0x3d, 0x57, 0x14, 0xc1, 0xc6, 0x0e, 0x3b, 0xff, 0x10, 0x63, 0x47,
	0x46, 0x94, 0xfc, 0x23, 0x08, 0x7f, 0x24, 0xbe, 0x8b, 0xd3, 0x73, 0x3c, 0x59, 0xf2, 0xef, 0xe3,
	0x3d, 0xfb, 0xde, 0xfb, 0x1d, 0x6c, 0xe3, 0x20, 0xe6, 0x0c, 0x19, 0x22, 0x57, 0xe8, 0x67, 0x0f,
	0x86, 0x42, 0x8e, 0xfc, 0xd3, 0xae, 0x3f, 0x4e, 0x78, 0x7c, 0xe6, 0x45, 0xb1, 0x44, 0x49, 0xda,
	0x65, 0xa2, 0x57, 0x22, 0x76, 0x36, 0xe1, 0xe6, 0x9b, 0xff, 0xc4, 0x43, 0xf5, 0x8a, 0x85, 0x22,
	0x10, 0x32, 0x51, 0x27, 0x7c, 0x9c, 0x70, 0x85, 0x1d, 0x0a, 0xed, 0x45, 0x48, 0x45, 0x72, 0xa4,
	0x78, 0xe7, 0x16, 0x50, 0x13, 0x7b, 0x7b, 0x72, 0x54, 0x28, 0x6f, 0xc3, 0x96, 0x89, 0x1e, 0x1e,
	0x9f, 0xf6, 0x0a, 0xf8, 0x2e, 0xdc, 0x31, 0xe1, 0x97, 0x32, 0x0c, 0xe5, 0x90, 0x8d, 0x0a, 0x4a,
	0xe1, 0xff, 0x82, 0xe3, 0xfe, 0xbc, 0x5b, 0xd3, 0xdf, 0x44, 0xf3, 0xe6, 0x1e, 0xc0, 0xbd, 0x14,
	0x3e, 0x12, 0x0a, 0xf7, 0x63, 0x14, 0x1f, 0x58, 0x50, 0xe6, 0xcd, 0x3e, 0x70, 0x1b, 0xee, 0x5b,
	0x78, 0x55, 0x86, 0x29, 0x81, 0xc7, 0x56, 0xc3, 0x4a, 0x5e, 0x6e, 0xd8, 0x86, 0x1b, 0xc5, 0x07,
	0x3c, 0x17, 0x2a, 0x4a, 0x90, 0x17, 0x16, 0xc5, 0x79, 0x94, 0x91, 0x5c, 0xb4, 0x05, 0x9b, 0xf9,
	0x6f, 0x3b, 0x08, 0x59, 0xf0, 0x29, 0x14, 0x0a, 0xf9, 0x7b, 0xf3, 0x87, 0x19, 0x60, 0x2e, 0xbd,
	0x06, 0x24, 0x45, 0x8f, 0x59, 0xcc, 0x86, 0xb3, 0x76, 0xaf, 0xc3, 0x86, 0xf6, 0x36, 0x23, 0xef,
	0xfc, 0x00, 0xb8, 0x94, 0xbe, 0x27, 0x08, 0x97, 0x4b, 0x67, 0x44, 0xba, 0xde, 0xb2, 0x31, 0xf2,
	0x96, 0xcc, 0x10, 0xdd, 0x59, 0x45, 0x92, 0xd5, 0x27, 0x5f, 0x60, 0x5d, 0x1f, 0x2b, 0xd2, 0xab,
	0xef, 0x32, 0x9f, 0xc2, 0x46, 0xb5, 0xbf, 0xc2, 0x55, 0x63, 0x68, 0xc9, 0x5e, 0x7d, 0x9b, 0xd2,
	0x90, 0x37, 0xaa, 0xfe, 0xdd, 0x81, 0x8d, 0x8a, 0xa5, 0x20, 0x4f, 0xea, 0x7b, 0x19, 0x8b, 0xd4,
	0xa8, 0x8d, 0x6f, 0xb0, 0xae, 0x6f, 0x96, 0xf5, 0x00, 0x2a, 0xd7, 0x94, 0xee, 0xad, 0xa8, 0xca,
	0xcb, 0xff, 0x72, 0xa0, 0xbd, 0x6c, 0x25, 0xc9, 0x53, 0x8b, 0xa7, 0x65, 0xe7, 0xe9, 0xb3, 0xc6,
	0x7a, 0xb3, 0xbb, 0x8a, 0xfd, 0xae, 0xd7, 0xdd, 0xf2, 0x00, 0xa9, 0xd7, 0xdd, 0x05, 0xc1, 0x42,
	0xc6, 0x00, 0xf3, 0xe4, 0x20, 0x8f, 0xed, 0x07, 0xa0, 0xc7, 0x0f, 0xed, 0xae, 0xa0, 0x98, 0xad,
	0xeb, 0x15, 0x2d, 0x74, 0xc8, 0xae, 0x75, 0xe4, 0x16, 0xf3, 0x8b, 0xf6, 0x56, 0x13, 0xe5, 0xb5,
	0x39, 0xac, 0x65, 0xe1, 0x45, 0x1e, 0x5a, 0xf4, 0x5a, 0xf2, 0xd1, 0x47, 0x35, 0xd9, 0x59, 0x99,
	0x83, 0xd7, 0xbf, 0x27, 0xae, 0x73, 0x3e, 0x71, 0x9d, 0xbf, 0x13, 0xd7, 0xf9, 0x39, 0x75, 0x5b,
	0xe7, 0x53, 0xb7, 0xf5, 0x67, 0xea, 0xb6, 0xde, 0xf5, 0x3e, 0x0a, 0x1c, 0x24, 0x7d, 0x2f, 0x90,
	0x43, 0x5f, 0xbb, 0x8c, 0x83, 0x01, 0x13, 0x23, 0xff, 0xb3, 0x76, 0x29, 0xe3, 0x59, 0xc4, 0x95,
	0x1f, 0xf5, 0xfb, 0x6b, 0xe9, 0xad, 0xbc, 0xfb, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x24, 0x1e, 0xdc,
	0xb4, 0xc0, 0x07, 0x00, 0x00,
}

func (m *QueryIsMaliciousRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIsMaliciousRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIsMaliciousRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryIsMaliciousResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIsMaliciousResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIsMaliciousResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryIsMaliciousURLRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIsMaliciousURLRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIsMaliciousURLRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryIsMaliciousIPv4Request) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIsMaliciousIPv4Request) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIsMaliciousIPv4Request) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryIsMaliciousHollomanRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIsMaliciousHollomanRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIsMaliciousHollomanRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetAttestationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAttestationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAttestationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetAttestationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAttestationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAttestationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryListArtifactAttestationsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListArtifactAttestationsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListArtifactAttestationsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryListArtifactAttestationsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListArtifactAttestationsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListArtifactAttestationsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryListAttesterAttestationsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListAttesterAttestationsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListAttesterAttestationsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryListAttesterAttestationsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListAttesterAttestationsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListAttesterAttestationsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetDisputeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDisputeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDisputeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetDisputeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDisputeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDisputeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryIsBlacklistedRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIsBlacklistedRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIsBlacklistedRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryIsBlacklistedResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIsBlacklistedResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIsBlacklistedResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryIsMaliciousRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryIsMaliciousResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryIsMaliciousURLRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryIsMaliciousIPv4Request) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryIsMaliciousHollomanRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetAttestationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetAttestationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryListArtifactAttestationsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryListArtifactAttestationsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryListAttesterAttestationsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryListAttesterAttestationsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetDisputeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetDisputeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryIsBlacklistedRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryIsBlacklistedResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryIsMaliciousRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIsMaliciousRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIsMaliciousRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIsMaliciousResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIsMaliciousResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIsMaliciousResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIsMaliciousURLRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIsMaliciousURLRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIsMaliciousURLRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIsMaliciousIPv4Request) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIsMaliciousIPv4Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIsMaliciousIPv4Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIsMaliciousHollomanRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIsMaliciousHollomanRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIsMaliciousHollomanRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAttestationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAttestationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAttestationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAttestationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAttestationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAttestationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListArtifactAttestationsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListArtifactAttestationsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListArtifactAttestationsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListArtifactAttestationsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListArtifactAttestationsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListArtifactAttestationsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListAttesterAttestationsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListAttesterAttestationsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListAttesterAttestationsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListAttesterAttestationsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListAttesterAttestationsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListAttesterAttestationsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDisputeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDisputeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDisputeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDisputeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDisputeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDisputeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIsBlacklistedRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIsBlacklistedRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIsBlacklistedRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIsBlacklistedResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIsBlacklistedResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIsBlacklistedResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
