#!/usr/bin/env bash
# Copyright (c) 2026 by Support Intelligence, Inc. All rights reserved.
# =============================================================================
#  ThreatAttest - Quick File Attestation Demo
#
#  Usage:
#    chmod +x attest_file.sh
#    ./attest_file.sh [FILE]
#
#  Examples:
#    ./attest_file.sh sample_malicious.txt
#    ./attest_file.sh sample_malicious.txt --dry-run
# =============================================================================

set -euo pipefail

BINARY="${BINARY:-../bin/threatattestd}"
CHAIN_ID="${CHAIN_ID:-threatattest-1}"
NODE="${NODE:-http://127.0.0.1:26657}"
KEY_NAME="${KEY_NAME:-attester}"
FEES="${FEES:-500utatst}"

# Colour helpers
CYAN="\033[0;36m"; GREEN="\033[0;32m"; YELLOW="\033[1;33m"
RED="\033[0;31m"; BOLD="\033[1m"; RESET="\033[0m"

info()    { echo -e "${CYAN}i${RESET}  $*"; }
success() { echo -e "${GREEN}OK${RESET}   $*"; }
warn()    { echo -e "${YELLOW}!!${RESET}   $*"; }
fatal()   { echo -e "${RED}ERR${RESET}  $*"; exit 1; }

echo -e "${BOLD}"
echo "  +----------------------------------------------------------+"
echo "  |      ThreatAttest -- File Attestation Demo               |"
echo "  +----------------------------------------------------------+"
echo -e "${RESET}"

# Preflight
[[ -x "$BINARY" ]] || fatal "threatattestd not found at $BINARY -- run: cd .. && go build -o bin/threatattestd ./cmd/threatattestd"
command -v jq &>/dev/null || warn "jq not found -- JSON output will not be pretty-printed"

# Arguments
TARGET_FILE="${1:-sample_malicious.txt}"
DRY_RUN="${2:-}"

[[ -f "$TARGET_FILE" ]] || fatal "File not found: $TARGET_FILE"

BASENAME=$(basename "$TARGET_FILE")
OUTPUT_JSON="${BASENAME%.*}_attestation.json"

SEVERITY="HIGH"
CONFIDENCE="90"
TTL="86400"
DESCRIPTION="Demo attestation generated by attest_file.sh"
TAGS="demo,sample"
CATEGORY="UNKNOWN"

info "File   : $TARGET_FILE"
info "Output : $OUTPUT_JSON"
info "Binary : $BINARY"
echo ""

# ---- Step 1: SHA-256 -------------------------------------------------------
echo -e "${BOLD}-- Step 1/4  Compute SHA-256 ---------------------------------${RESET}"
SHA256_PREVIEW=$(sha256sum "$TARGET_FILE" 2>/dev/null | awk '{print $1}' || shasum -a 256 "$TARGET_FILE" 2>/dev/null | awk '{print $1}' || echo "unavailable")
info "sha256sum : $SHA256_PREVIEW"
echo ""

# ---- Step 2: attest-file ---------------------------------------------------
echo -e "${BOLD}-- Step 2/4  Run threatattestd attest-file -------------------${RESET}"

if [[ "$DRY_RUN" == "--dry-run" ]]; then
    echo "Running with --dry-run (no file written)"
    echo ""
    "$BINARY" attest-file "$TARGET_FILE" \
        --severity    "$SEVERITY" \
        --confidence  "$CONFIDENCE" \
        --ttl         "$TTL" \
        --description "$DESCRIPTION" \
        --tags        "$TAGS" \
        --category    "$CATEGORY" \
        --chain-id    "$CHAIN_ID" \
        --dry-run
    echo ""
    success "Dry-run complete -- no file written."
    exit 0
fi

"$BINARY" attest-file "$TARGET_FILE" \
    --severity    "$SEVERITY" \
    --confidence  "$CONFIDENCE" \
    --ttl         "$TTL" \
    --description "$DESCRIPTION" \
    --tags        "$TAGS" \
    --category    "$CATEGORY" \
    --chain-id    "$CHAIN_ID" \
    --output      "$OUTPUT_JSON"

echo ""

# ---- Step 3: Inspect spec --------------------------------------------------
echo -e "${BOLD}-- Step 3/4  Inspect attestation spec -----------------------${RESET}"

[[ -f "$OUTPUT_JSON" ]] || fatal "Expected output file not found: $OUTPUT_JSON"

if command -v jq &>/dev/null; then
    SHA256=$(jq -r '.artifact_sha256'      "$OUTPUT_JSON")
    SEVERITY_OUT=$(jq -r '.severity'       "$OUTPUT_JSON")
    CONFIDENCE_OUT=$(jq -r '.confidence'   "$OUTPUT_JSON")
    TTL_OUT=$(jq -r '.ttl_seconds'         "$OUTPUT_JSON")
    DESCRIPTION_OUT=$(jq -r '.description' "$OUTPUT_JSON")
    TAGS_OUT=$(jq -r '.tags | join(",")'   "$OUTPUT_JSON")
    CATS_OUT=$(jq -r '.threat_category | join(",")'  "$OUTPUT_JSON")
    echo ""
    success "Attestation spec:"
    echo ""
    jq . "$OUTPUT_JSON"
else
    SHA256=$(grep -o '"artifact_sha256":"[^"]*"' "$OUTPUT_JSON" | cut -d'"' -f4)
    SEVERITY_OUT="$SEVERITY"; CONFIDENCE_OUT="$CONFIDENCE"; TTL_OUT="$TTL"
    DESCRIPTION_OUT="$DESCRIPTION"; TAGS_OUT="$TAGS"; CATS_OUT="$CATEGORY"
    echo ""
    success "Attestation spec:"
    echo ""
    cat "$OUTPUT_JSON"
fi
echo ""

# ---- Step 4: Broadcast instructions ----------------------------------------
echo -e "${BOLD}-- Step 4/4  Broadcast to ThreatAttest chain ----------------${RESET}"
echo ""
info "To publish this attestation on-chain, run:"
echo ""
echo "  $BINARY tx attestation publish "
echo "    --artifact-sha256 $SHA256 "
echo "    --artifact-type   FILE "
echo "    --severity        $SEVERITY_OUT "
echo "    --confidence      $CONFIDENCE_OUT "
echo "    --ttl             $TTL_OUT "
echo "    --description     "$DESCRIPTION_OUT" "
echo "    --tags            "$TAGS_OUT" "
echo "    --category        "$CATS_OUT" "
echo "    --from            $KEY_NAME "
echo "    --chain-id        $CHAIN_ID "
echo "    --node            $NODE "
echo "    --fees            $FEES "
echo "    --yes"
echo ""

info "To query whether the file is malicious:"
echo ""
echo "  $BINARY query attestation is-malicious "
echo "    --sha256  $SHA256 "
echo "    --node    $NODE"
echo ""

success "Done.  Spec saved to: $OUTPUT_JSON"
echo ""
echo "See MANPAGE.md for the full command reference."
