// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: threatattest/ipfsverify/v1/query.proto

package pb

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryPendingJobsRequest struct {
	MaxCount uint32 `protobuf:"varint,1,opt,name=max_count,json=maxCount,proto3" json:"max_count,omitempty"`
}

func (m *QueryPendingJobsRequest) Reset()         { *m = QueryPendingJobsRequest{} }
func (m *QueryPendingJobsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPendingJobsRequest) ProtoMessage()    {}
func (*QueryPendingJobsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_71d18e520c42a182, []int{0}
}
func (m *QueryPendingJobsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPendingJobsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPendingJobsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPendingJobsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPendingJobsRequest.Merge(m, src)
}
func (m *QueryPendingJobsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPendingJobsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPendingJobsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPendingJobsRequest proto.InternalMessageInfo

func (m *QueryPendingJobsRequest) GetMaxCount() uint32 {
	if m != nil {
		return m.MaxCount
	}
	return 0
}

type QueryPendingJobsResponse struct {
	Jobs []*VerificationJob `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
}

func (m *QueryPendingJobsResponse) Reset()         { *m = QueryPendingJobsResponse{} }
func (m *QueryPendingJobsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPendingJobsResponse) ProtoMessage()    {}
func (*QueryPendingJobsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_71d18e520c42a182, []int{1}
}
func (m *QueryPendingJobsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPendingJobsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPendingJobsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPendingJobsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPendingJobsResponse.Merge(m, src)
}
func (m *QueryPendingJobsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPendingJobsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPendingJobsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPendingJobsResponse proto.InternalMessageInfo

func (m *QueryPendingJobsResponse) GetJobs() []*VerificationJob {
	if m != nil {
		return m.Jobs
	}
	return nil
}

// VerificationJob mirrors the on-chain job type for query responses.
type VerificationJob struct {
	JobId          string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AttestationId  string `protobuf:"bytes,2,opt,name=attestation_id,json=attestationId,proto3" json:"attestation_id,omitempty"`
	RuleId         string `protobuf:"bytes,3,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Cid            string `protobuf:"bytes,4,opt,name=cid,proto3" json:"cid,omitempty"`
	ExpectedSha256 string `protobuf:"bytes,5,opt,name=expected_sha256,json=expectedSha256,proto3" json:"expected_sha256,omitempty"`
	SubmittedBy    string `protobuf:"bytes,6,opt,name=submitted_by,json=submittedBy,proto3" json:"submitted_by,omitempty"`
	Status         int32  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Attempts       uint32 `protobuf:"varint,8,opt,name=attempts,proto3" json:"attempts,omitempty"`
}

func (m *VerificationJob) Reset()         { *m = VerificationJob{} }
func (m *VerificationJob) String() string { return proto.CompactTextString(m) }
func (*VerificationJob) ProtoMessage()    {}
func (*VerificationJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_71d18e520c42a182, []int{2}
}
func (m *VerificationJob) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VerificationJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VerificationJob.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VerificationJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationJob.Merge(m, src)
}
func (m *VerificationJob) XXX_Size() int {
	return m.Size()
}
func (m *VerificationJob) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationJob.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationJob proto.InternalMessageInfo

func (m *VerificationJob) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *VerificationJob) GetAttestationId() string {
	if m != nil {
		return m.AttestationId
	}
	return ""
}

func (m *VerificationJob) GetRuleId() string {
	if m != nil {
		return m.RuleId
	}
	return ""
}

func (m *VerificationJob) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *VerificationJob) GetExpectedSha256() string {
	if m != nil {
		return m.ExpectedSha256
	}
	return ""
}

func (m *VerificationJob) GetSubmittedBy() string {
	if m != nil {
		return m.SubmittedBy
	}
	return ""
}

func (m *VerificationJob) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *VerificationJob) GetAttempts() uint32 {
	if m != nil {
		return m.Attempts
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryPendingJobsRequest)(nil), "threatattest.ipfsverify.QueryPendingJobsRequest")
	proto.RegisterType((*QueryPendingJobsResponse)(nil), "threatattest.ipfsverify.QueryPendingJobsResponse")
	proto.RegisterType((*VerificationJob)(nil), "threatattest.ipfsverify.VerificationJob")
}

func init() {
	proto.RegisterFile("threatattest/ipfsverify/v1/query.proto", fileDescriptor_71d18e520c42a182)
}

var fileDescriptor_71d18e520c42a182 = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4f, 0x8b, 0xd3, 0x40,
	0x14, 0xef, 0xd8, 0x4d, 0xb6, 0xfb, 0xea, 0xee, 0xca, 0x80, 0x76, 0x58, 0x21, 0xd4, 0x82, 0x9a,
	0x53, 0xe2, 0xb6, 0xd8, 0x93, 0xa7, 0x7a, 0x6a, 0x41, 0xd0, 0x08, 0x22, 0x5e, 0x4a, 0x26, 0x99,
	0x36, 0x53, 0x4c, 0x26, 0xcd, 0x4c, 0x4a, 0x82, 0x5f, 0xc2, 0x8f, 0xe5, 0xb1, 0x47, 0x8f, 0xd2,
	0x7e, 0x0b, 0x4f, 0x32, 0x53, 0xab, 0x51, 0xe9, 0xc1, 0xd3, 0xcc, 0xef, 0xcf, 0x9b, 0x79, 0xfc,
	0xde, 0x83, 0x27, 0x2a, 0x29, 0x58, 0xa8, 0x42, 0xa5, 0x98, 0x54, 0x3e, 0xcf, 0x17, 0x72, 0xc3,
	0x0a, 0xbe, 0xa8, 0xfd, 0xcd, 0xad, 0xbf, 0x2e, 0x59, 0x51, 0x7b, 0x79, 0x21, 0x94, 0xc0, 0xbd,
	0xa6, 0xcf, 0xfb, 0xed, 0x1b, 0x8c, 0xa1, 0xf7, 0x46, 0xfb, 0x5e, 0xb3, 0x2c, 0xe6, 0xd9, 0x72,
	0x26, 0xa8, 0x0c, 0xd8, 0xba, 0x64, 0x52, 0xe1, 0x87, 0x70, 0x91, 0x86, 0xd5, 0x3c, 0x12, 0x65,
	0xa6, 0x08, 0xea, 0x23, 0xf7, 0x32, 0xe8, 0xa4, 0x61, 0xf5, 0x52, 0xe3, 0xc1, 0x7b, 0x20, 0xff,
	0xd6, 0xc9, 0x5c, 0x64, 0x92, 0xe1, 0x17, 0x70, 0xb6, 0x12, 0x54, 0x12, 0xd4, 0x6f, 0xbb, 0xdd,
	0xa1, 0xeb, 0x9d, 0xf8, 0xdb, 0x7b, 0xa7, 0x0f, 0x1e, 0x85, 0x8a, 0x8b, 0x6c, 0x26, 0x68, 0x60,
	0xaa, 0x06, 0xdf, 0x11, 0x5c, 0xff, 0xa5, 0xe0, 0xfb, 0x60, 0xaf, 0x04, 0x9d, 0xf3, 0xd8, 0xf4,
	0x71, 0x11, 0x58, 0x2b, 0x41, 0xa7, 0x31, 0x7e, 0x0c, 0x57, 0x87, 0x57, 0x8d, 0x51, 0xcb, 0x77,
	0x8c, 0x7c, 0xd9, 0x60, 0xa7, 0x31, 0xee, 0xc1, 0x79, 0x51, 0x7e, 0x64, 0x5a, 0x6f, 0x1b, 0xdd,
	0xd6, 0x70, 0x1a, 0xe3, 0x7b, 0xd0, 0x8e, 0x78, 0x4c, 0xce, 0x0c, 0xa9, 0xaf, 0xf8, 0x29, 0x5c,
	0xb3, 0x2a, 0x67, 0x91, 0x62, 0xf1, 0x5c, 0x26, 0xe1, 0xf0, 0xf9, 0x98, 0x58, 0x46, 0xbd, 0x3a,
	0xd2, 0x6f, 0x0d, 0x8b, 0x1f, 0xc1, 0x5d, 0x59, 0xd2, 0x94, 0x2b, 0xed, 0xa4, 0x35, 0xb1, 0x8d,
	0xab, 0xfb, 0x8b, 0x9b, 0xd4, 0xf8, 0x01, 0xd8, 0xba, 0x87, 0x52, 0x92, 0xf3, 0x3e, 0x72, 0xad,
	0xe0, 0x27, 0xc2, 0x37, 0xd0, 0xd1, 0xfd, 0xa5, 0xb9, 0x92, 0xa4, 0x73, 0x88, 0xf5, 0x88, 0x87,
	0x9f, 0xc0, 0x32, 0xb1, 0xe2, 0x02, 0xba, 0x8d, 0x68, 0xf1, 0xb3, 0x93, 0x21, 0x9e, 0x98, 0xde,
	0xcd, 0xed, 0x7f, 0x54, 0x1c, 0xe6, 0x36, 0x79, 0xf5, 0x65, 0xe7, 0xa0, 0xed, 0xce, 0x41, 0xdf,
	0x76, 0x0e, 0xfa, 0xbc, 0x77, 0x5a, 0xdb, 0xbd, 0xd3, 0xfa, 0xba, 0x77, 0x5a, 0x1f, 0x46, 0x4b,
	0xae, 0x92, 0x92, 0x7a, 0x91, 0x48, 0xfd, 0x3f, 0x36, 0x2e, 0x4a, 0x42, 0x9e, 0xf9, 0x55, 0x73,
	0xf3, 0x54, 0x9d, 0x33, 0xe9, 0xe7, 0x94, 0xda, 0x66, 0xf5, 0x46, 0x3f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x3d, 0x8c, 0xb8, 0x7b, 0xa4, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	PendingJobs(ctx context.Context, in *QueryPendingJobsRequest, opts ...grpc.CallOption) (*QueryPendingJobsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) PendingJobs(ctx context.Context, in *QueryPendingJobsRequest, opts ...grpc.CallOption) (*QueryPendingJobsResponse, error) {
	out := new(QueryPendingJobsResponse)
	err := c.cc.Invoke(ctx, "/threatattest.ipfsverify.Query/PendingJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	PendingJobs(context.Context, *QueryPendingJobsRequest) (*QueryPendingJobsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) PendingJobs(ctx context.Context, req *QueryPendingJobsRequest) (*QueryPendingJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PendingJobs not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_PendingJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPendingJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PendingJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/threatattest.ipfsverify.Query/PendingJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PendingJobs(ctx, req.(*QueryPendingJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "threatattest.ipfsverify.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PendingJobs",
			Handler:    _Query_PendingJobs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "threatattest/ipfsverify/v1/query.proto",
}

func (m *QueryPendingJobsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPendingJobsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPendingJobsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxCount != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.MaxCount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryPendingJobsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPendingJobsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPendingJobsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Jobs) > 0 {
		for iNdEx := len(m.Jobs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Jobs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *VerificationJob) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VerificationJob) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VerificationJob) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Attempts != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Attempts))
		i--
		dAtA[i] = 0x40
	}
	if m.Status != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x38
	}
	if len(m.SubmittedBy) > 0 {
		i -= len(m.SubmittedBy)
		copy(dAtA[i:], m.SubmittedBy)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.SubmittedBy)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.ExpectedSha256) > 0 {
		i -= len(m.ExpectedSha256)
		copy(dAtA[i:], m.ExpectedSha256)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ExpectedSha256)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Cid) > 0 {
		i -= len(m.Cid)
		copy(dAtA[i:], m.Cid)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Cid)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.RuleId) > 0 {
		i -= len(m.RuleId)
		copy(dAtA[i:], m.RuleId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RuleId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.AttestationId) > 0 {
		i -= len(m.AttestationId)
		copy(dAtA[i:], m.AttestationId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.AttestationId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.JobId) > 0 {
		i -= len(m.JobId)
		copy(dAtA[i:], m.JobId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.JobId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryPendingJobsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxCount != 0 {
		n += 1 + sovQuery(uint64(m.MaxCount))
	}
	return n
}

func (m *QueryPendingJobsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Jobs) > 0 {
		for _, e := range m.Jobs {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *VerificationJob) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.JobId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.AttestationId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.RuleId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Cid)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.ExpectedSha256)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.SubmittedBy)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovQuery(uint64(m.Status))
	}
	if m.Attempts != 0 {
		n += 1 + sovQuery(uint64(m.Attempts))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryPendingJobsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPendingJobsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPendingJobsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCount", wireType)
			}
			m.MaxCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPendingJobsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPendingJobsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPendingJobsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Jobs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Jobs = append(m.Jobs, &VerificationJob{})
			if err := m.Jobs[len(m.Jobs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VerificationJob) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VerificationJob: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VerificationJob: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JobId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestationId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AttestationId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RuleId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RuleId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpectedSha256", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExpectedSha256 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmittedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubmittedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attempts", wireType)
			}
			m.Attempts = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Attempts |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
