// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: threatattest/ipfsverify/v1/tx.proto

package pb

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// VerificationReport carries the outcome of fetching and hashing an IPFS CID.
type VerificationReport struct {
	JobId          string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AttestationId  string `protobuf:"bytes,2,opt,name=attestation_id,json=attestationId,proto3" json:"attestation_id,omitempty"`
	RuleId         string `protobuf:"bytes,3,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Cid            string `protobuf:"bytes,4,opt,name=cid,proto3" json:"cid,omitempty"`
	ExpectedSha256 string `protobuf:"bytes,5,opt,name=expected_sha256,json=expectedSha256,proto3" json:"expected_sha256,omitempty"`
	ActualSha256   string `protobuf:"bytes,6,opt,name=actual_sha256,json=actualSha256,proto3" json:"actual_sha256,omitempty"`
	Matched        bool   `protobuf:"varint,7,opt,name=matched,proto3" json:"matched,omitempty"`
	VerifiedAt     int64  `protobuf:"varint,8,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	VerifiedBy     string `protobuf:"bytes,9,opt,name=verified_by,json=verifiedBy,proto3" json:"verified_by,omitempty"`
	ErrorMsg       string `protobuf:"bytes,10,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
}

func (m *VerificationReport) Reset()         { *m = VerificationReport{} }
func (m *VerificationReport) String() string { return proto.CompactTextString(m) }
func (*VerificationReport) ProtoMessage()    {}
func (*VerificationReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_cca38fd5093834bb, []int{0}
}
func (m *VerificationReport) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VerificationReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VerificationReport.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VerificationReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationReport.Merge(m, src)
}
func (m *VerificationReport) XXX_Size() int {
	return m.Size()
}
func (m *VerificationReport) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationReport.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationReport proto.InternalMessageInfo

func (m *VerificationReport) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *VerificationReport) GetAttestationId() string {
	if m != nil {
		return m.AttestationId
	}
	return ""
}

func (m *VerificationReport) GetRuleId() string {
	if m != nil {
		return m.RuleId
	}
	return ""
}

func (m *VerificationReport) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *VerificationReport) GetExpectedSha256() string {
	if m != nil {
		return m.ExpectedSha256
	}
	return ""
}

func (m *VerificationReport) GetActualSha256() string {
	if m != nil {
		return m.ActualSha256
	}
	return ""
}

func (m *VerificationReport) GetMatched() bool {
	if m != nil {
		return m.Matched
	}
	return false
}

func (m *VerificationReport) GetVerifiedAt() int64 {
	if m != nil {
		return m.VerifiedAt
	}
	return 0
}

func (m *VerificationReport) GetVerifiedBy() string {
	if m != nil {
		return m.VerifiedBy
	}
	return ""
}

func (m *VerificationReport) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

// MsgSubmitVerificationReport is submitted by the off-chain verifier daemon
// (running as a whitelisted relayer) after fetching and hashing CID content.
type MsgSubmitVerificationReport struct {
	Sender string              `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Report *VerificationReport `protobuf:"bytes,2,opt,name=report,proto3" json:"report,omitempty"`
}

func (m *MsgSubmitVerificationReport) Reset()         { *m = MsgSubmitVerificationReport{} }
func (m *MsgSubmitVerificationReport) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitVerificationReport) ProtoMessage()    {}
func (*MsgSubmitVerificationReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_cca38fd5093834bb, []int{1}
}
func (m *MsgSubmitVerificationReport) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitVerificationReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitVerificationReport.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitVerificationReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitVerificationReport.Merge(m, src)
}
func (m *MsgSubmitVerificationReport) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitVerificationReport) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitVerificationReport.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitVerificationReport proto.InternalMessageInfo

func (m *MsgSubmitVerificationReport) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgSubmitVerificationReport) GetReport() *VerificationReport {
	if m != nil {
		return m.Report
	}
	return nil
}

type MsgSubmitVerificationReportResponse struct {
}

func (m *MsgSubmitVerificationReportResponse) Reset()         { *m = MsgSubmitVerificationReportResponse{} }
func (m *MsgSubmitVerificationReportResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitVerificationReportResponse) ProtoMessage()    {}
func (*MsgSubmitVerificationReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cca38fd5093834bb, []int{2}
}
func (m *MsgSubmitVerificationReportResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitVerificationReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitVerificationReportResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitVerificationReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitVerificationReportResponse.Merge(m, src)
}
func (m *MsgSubmitVerificationReportResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitVerificationReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitVerificationReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitVerificationReportResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*VerificationReport)(nil), "threatattest.ipfsverify.VerificationReport")
	proto.RegisterType((*MsgSubmitVerificationReport)(nil), "threatattest.ipfsverify.MsgSubmitVerificationReport")
	proto.RegisterType((*MsgSubmitVerificationReportResponse)(nil), "threatattest.ipfsverify.MsgSubmitVerificationReportResponse")
}

func init() {
	proto.RegisterFile("threatattest/ipfsverify/v1/tx.proto", fileDescriptor_cca38fd5093834bb)
}

var fileDescriptor_cca38fd5093834bb = []byte{
	// 468 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x73, 0x0d, 0x71, 0x92, 0x17, 0x5a, 0xd0, 0x49, 0x90, 0x53, 0x2a, 0x99, 0x28, 0x51,
	0x45, 0x54, 0x24, 0x5b, 0xa4, 0xc0, 0x80, 0x58, 0x28, 0x53, 0x86, 0x2c, 0xae, 0xc4, 0xc0, 0x12,
	0x9d, 0x7d, 0x57, 0xfb, 0xaa, 0x3a, 0x67, 0xdd, 0x5d, 0xaa, 0x64, 0x43, 0x2c, 0x6c, 0x88, 0x2f,
	0xc0, 0x77, 0xe8, 0x87, 0x60, 0x60, 0xec, 0xc8, 0x88, 0x92, 0xa1, 0x5f, 0x03, 0xf9, 0x62, 0x43,
	0x2a, 0x48, 0x87, 0x6e, 0x7e, 0xff, 0xff, 0xef, 0x3d, 0x3f, 0xfd, 0xed, 0x07, 0x7d, 0x93, 0x28,
	0x4e, 0x0d, 0x35, 0x86, 0x6b, 0xe3, 0x8b, 0xec, 0x54, 0x5f, 0x70, 0x25, 0x4e, 0x17, 0xfe, 0xc5,
	0x73, 0xdf, 0xcc, 0xbd, 0x4c, 0x49, 0x23, 0x71, 0x7b, 0x13, 0xf2, 0xfe, 0x42, 0x9d, 0x76, 0x24,
	0x75, 0x2a, 0xb5, 0x9f, 0xea, 0x38, 0x6f, 0x48, 0x75, 0xbc, 0xee, 0xe8, 0x7d, 0xdf, 0x01, 0xfc,
	0x3e, 0x67, 0x44, 0x44, 0x8d, 0x90, 0xd3, 0x80, 0x67, 0x52, 0x19, 0xfc, 0x08, 0x9c, 0x33, 0x19,
	0x4e, 0x04, 0x23, 0xa8, 0x8b, 0x06, 0xcd, 0xa0, 0x76, 0x26, 0xc3, 0x11, 0xc3, 0x07, 0xb0, 0xb7,
	0x9e, 0x6d, 0xd9, 0xdc, 0xde, 0xb1, 0xf6, 0xee, 0x86, 0x3a, 0x62, 0xb8, 0x0d, 0x75, 0x35, 0x3b,
	0xe7, 0xb9, 0x5f, 0xb5, 0xbe, 0x93, 0x97, 0x23, 0x86, 0x1f, 0x42, 0x35, 0x12, 0x8c, 0xdc, 0xb3,
	0x62, 0xfe, 0x88, 0x9f, 0xc2, 0x03, 0x3e, 0xcf, 0x78, 0x64, 0x38, 0x9b, 0xe8, 0x84, 0x0e, 0x5f,
	0xbe, 0x22, 0x35, 0xeb, 0xee, 0x95, 0xf2, 0x89, 0x55, 0x71, 0x1f, 0x76, 0x69, 0x64, 0x66, 0xf4,
	0xbc, 0xc4, 0x1c, 0x8b, 0xdd, 0x5f, 0x8b, 0x05, 0x44, 0xa0, 0x9e, 0x52, 0x13, 0x25, 0x9c, 0x91,
	0x7a, 0x17, 0x0d, 0x1a, 0x41, 0x59, 0xe2, 0x27, 0xd0, 0xb2, 0x51, 0x08, 0xce, 0x26, 0xd4, 0x90,
	0x46, 0x17, 0x0d, 0xaa, 0x01, 0x94, 0xd2, 0x5b, 0x73, 0x03, 0x08, 0x17, 0xa4, 0x69, 0xa7, 0xff,
	0x01, 0x8e, 0x17, 0x78, 0x1f, 0x9a, 0x5c, 0x29, 0xa9, 0x26, 0xa9, 0x8e, 0x09, 0x58, 0xbb, 0x61,
	0x85, 0xb1, 0x8e, 0x7b, 0x9f, 0x11, 0xec, 0x8f, 0x75, 0x7c, 0x32, 0x0b, 0x53, 0x61, 0xfe, 0x93,
	0xe7, 0x63, 0x70, 0x34, 0x9f, 0x32, 0xae, 0x8a, 0x3c, 0x8b, 0x0a, 0xbf, 0x03, 0x47, 0x59, 0xc2,
	0x06, 0xd9, 0x1a, 0x3e, 0xf3, 0xb6, 0x7c, 0x41, 0xef, 0xdf, 0xa1, 0x41, 0xd1, 0xfa, 0xba, 0xf5,
	0xe9, 0xfa, 0xf2, 0xb0, 0x98, 0xd8, 0x3b, 0x80, 0xfe, 0x2d, 0x8b, 0x04, 0x5c, 0x67, 0x72, 0xaa,
	0xf9, 0xf0, 0x1b, 0x82, 0xea, 0x58, 0xc7, 0xf8, 0x0b, 0x02, 0xb2, 0x75, 0xeb, 0x17, 0x5b, 0xb7,
	0xb9, 0xe5, 0x15, 0x9d, 0x37, 0x77, 0xe9, 0x2a, 0x17, 0xeb, 0xd4, 0x3e, 0x5e, 0x5f, 0x1e, 0xa2,
	0xe3, 0xf1, 0x8f, 0xa5, 0x8b, 0xae, 0x96, 0x2e, 0xfa, 0xb5, 0x74, 0xd1, 0xd7, 0x95, 0x5b, 0xb9,
	0x5a, 0xb9, 0x95, 0x9f, 0x2b, 0xb7, 0xf2, 0xe1, 0x28, 0x16, 0x26, 0x99, 0x85, 0x5e, 0x24, 0x53,
	0xff, 0xc6, 0x4d, 0x44, 0x09, 0x15, 0x53, 0x7f, 0xbe, 0x79, 0x1b, 0x66, 0x91, 0x71, 0xed, 0x67,
	0x61, 0xe8, 0xd8, 0xbf, 0xfd, 0xe8, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x14, 0x59, 0xed, 0x2b,
	0x46, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SubmitVerificationReport(ctx context.Context, in *MsgSubmitVerificationReport, opts ...grpc.CallOption) (*MsgSubmitVerificationReportResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubmitVerificationReport(ctx context.Context, in *MsgSubmitVerificationReport, opts ...grpc.CallOption) (*MsgSubmitVerificationReportResponse, error) {
	out := new(MsgSubmitVerificationReportResponse)
	err := c.cc.Invoke(ctx, "/threatattest.ipfsverify.Msg/SubmitVerificationReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SubmitVerificationReport(context.Context, *MsgSubmitVerificationReport) (*MsgSubmitVerificationReportResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SubmitVerificationReport(ctx context.Context, req *MsgSubmitVerificationReport) (*MsgSubmitVerificationReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitVerificationReport not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SubmitVerificationReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitVerificationReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitVerificationReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/threatattest.ipfsverify.Msg/SubmitVerificationReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitVerificationReport(ctx, req.(*MsgSubmitVerificationReport))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "threatattest.ipfsverify.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitVerificationReport",
			Handler:    _Msg_SubmitVerificationReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "threatattest/ipfsverify/v1/tx.proto",
}

func (m *VerificationReport) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VerificationReport) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VerificationReport) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ErrorMsg) > 0 {
		i -= len(m.ErrorMsg)
		copy(dAtA[i:], m.ErrorMsg)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ErrorMsg)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.VerifiedBy) > 0 {
		i -= len(m.VerifiedBy)
		copy(dAtA[i:], m.VerifiedBy)
		i = encodeVarintTx(dAtA, i, uint64(len(m.VerifiedBy)))
		i--
		dAtA[i] = 0x4a
	}
	if m.VerifiedAt != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.VerifiedAt))
		i--
		dAtA[i] = 0x40
	}
	if m.Matched {
		i--
		if m.Matched {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if len(m.ActualSha256) > 0 {
		i -= len(m.ActualSha256)
		copy(dAtA[i:], m.ActualSha256)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ActualSha256)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.ExpectedSha256) > 0 {
		i -= len(m.ExpectedSha256)
		copy(dAtA[i:], m.ExpectedSha256)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ExpectedSha256)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Cid) > 0 {
		i -= len(m.Cid)
		copy(dAtA[i:], m.Cid)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Cid)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.RuleId) > 0 {
		i -= len(m.RuleId)
		copy(dAtA[i:], m.RuleId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RuleId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.AttestationId) > 0 {
		i -= len(m.AttestationId)
		copy(dAtA[i:], m.AttestationId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AttestationId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.JobId) > 0 {
		i -= len(m.JobId)
		copy(dAtA[i:], m.JobId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.JobId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitVerificationReport) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitVerificationReport) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitVerificationReport) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Report != nil {
		{
			size, err := m.Report.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitVerificationReportResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitVerificationReportResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitVerificationReportResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *VerificationReport) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.JobId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AttestationId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RuleId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Cid)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ExpectedSha256)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ActualSha256)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Matched {
		n += 2
	}
	if m.VerifiedAt != 0 {
		n += 1 + sovTx(uint64(m.VerifiedAt))
	}
	l = len(m.VerifiedBy)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ErrorMsg)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitVerificationReport) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Report != nil {
		l = m.Report.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitVerificationReportResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *VerificationReport) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VerificationReport: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VerificationReport: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JobId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestationId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AttestationId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RuleId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RuleId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpectedSha256", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExpectedSha256 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActualSha256", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActualSha256 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Matched", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Matched = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifiedAt", wireType)
			}
			m.VerifiedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VerifiedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifiedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerifiedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorMsg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ErrorMsg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitVerificationReport) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitVerificationReport: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitVerificationReport: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Report", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Report == nil {
				m.Report = &VerificationReport{}
			}
			if err := m.Report.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitVerificationReportResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitVerificationReportResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitVerificationReportResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
